# Python Practice: books.csv Analysis

## Importing the required libraries

In [2]:
# import libraries for data manipulation
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

## Data Structure

In [7]:
# Read the data
df = pd.read_csv('books.csv')
df.shape

(5000, 10)

In [8]:
df.describe()

,average_rating,isbn13,num_pages,ratings_count,text_reviews_count,year
count,5000.000000,5.000000e+03,4967.000000,5.000000e+03,5000.000000,5000.000000
mean,3.931932,9.752758e+12,341.094021,2.017549e+04,592.688600,2000.131800
std,0.348741,5.129254e+11,230.986115,1.175026e+05,2539.539004,8.069043
min,0.000000,8.987060e+09,1.000000,0.000000e+00,0.000000,1913.000000
25%,3.770000,9.780345e+12,200.000000,1.050000e+02,9.000000,1998.000000
50%,3.960000,9.780571e+12,304.000000,7.915000e+02,49.000000,2003.000000
75%,4.140000,9.780871e+12,416.500000,5.348750e+03,249.000000,2005.000000
max,5.000000,9.789879e+12,3342.000000,2.457092e+06,55843.000000,2019.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               5000 non-null   object
 1   author              5000 non-null   object
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64
 4   language_code       4923 non-null   object
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64
 7   text_reviews_count  5000 non-null   int64
 8   publisher           5000 non-null   object
 9   year                5000 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB

In [10]:
# Count how many books have average rating > 4
count = (df['average_rating'] > 4).sum()

print(f"Number of books with average rating > 4: {count}")

Number of books with average rating > 4: 2115

In [11]:
df[(df['average_rating'] > 4.5) & (df['ratings_count'] < 10)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
63,鋼之鍊金術師 9,Hiromu Arakawa,4.57,9789861156521,NaN,184.0,4,0,東立,2004
178,鋼之鍊金術師 6,Hiromu Arakawa,4.58,9789861146140,NaN,191.0,5,0,東立,2004
224,Stargirl LitPlans on CD,Mary B. Collins,4.86,9781583372920,eng,210.0,5,0,Teacher's Pet Publications,2005
454,Literature Circle Guide: Bridge to Terabithia:...,Tara MacCarthy,5.00,9780439271714,eng,32.0,4,1,Teaching Resources,2002
584,Falling Angels (Luc Actar #1),Melissa M. Garcia,4.67,9780595377107,eng,216.0,1,0,iUniverse,2006
681,Fanning the Flame: Bible Cross and Mission,Chris Green,5.00,9780310249870,eng,336.0,1,1,Zondervan,2003
696,Tyrannosaurus Wrecks (Stanley #1),Laura Driscoll,5.00,9780786845033,eng,24.0,2,1,Disney Press,2003
741,The John Deere Two-Cylinder Tractor Encycloped...,Don Macmillan,4.75,9780760329634,eng,256.0,4,0,Voyageur Press,2007
757,The American Campaign: U.S. Presidential Campa...,James E. Campbell,5.00,9780890969403,eng,314.0,0,0,Texas A&M University Press,2000
1837,The Goon Show Volume 4: My Knees Have Fallen ...,NOT A BOOK,5.00,9780563388692,eng,2.0,3,0,BBC Physical Audio,1996
1856,鋼之鍊金術師 10,Hiromu Arakawa,4.60,9789861156538,NaN,188.0,3,0,東立,2005
1960,Wissenschaft der Logik: Die Lehre Vom Begriff ...,Georg Wilhelm Friedrich Hegel,4.78,9783787307678,ger,337.0,0,0,F. Meiner,1994
2244,Getting a Grip on the Basics: Building a Firm ...,Beth A. Jones,4.67,9781577948261,eng,124.0,9,0,Harrison House,2006
2496,Come Away My Beloved,Frances J. Roberts,4.58,9781593109158,eng,192.0,8,0,Barbour Books,2005
3178,Organizational Architecture: Designs for Chang...,David A. Nadler,4.62,9781555424435,eng,304.0,2,0,Jossey-Bass,1992
3438,Bill Gates: Computer Legend (Famous Lives),Sara Barton-Wood,5.00,9780739844328,eng,48.0,0,0,Raintree,2001
3706,A Wife After God's Own Heart Growth and Study ...,Elizabeth George,4.69,9780736911689,eng,160.0,9,1,Harvest House Publishers,2004
3833,His Princess Devotional: A Royal Encounter Wit...,Sheri Rose Shepherd,5.00,9781590529621,eng,240.0,2,0,Multnomah,2007
3909,Little Big Book for God's Children,Alice Wong,4.88,9780941807555,en-US,352.0,8,0,Welcome Books,2001
3927,Colossians and Philemon: A Critical and Exeget...,R. McL. Wilson,5.00,9780567044716,eng,512.0,1,0,T&T Clark Int'l,2005
4108,Willem de Kooning: Late Paintings,Julie Sylvester,5.00,9783829602266,eng,83.0,1,0,Schirmer Mosel,2006
4415,Corvette,Jerry Burton,4.83,9780883631218,eng,320.0,6,1,Universe Publishing(NY),2006
4455,The Complete Theory Fun Factory: Music Theory ...,Ian Martin,5.00,9780851621814,eng,96.0,1,0,Boosey & Hawkes Inc,2004
4917,Taxation of Mineral Rents,Ross Garnaut,5.00,9780198284543,eng,350.0,1,0,Oxford University Press USA,1983
4933,Oliver Wendell Holmes in Paris: Medicine Theo...,William C. Dowling,5.00,9781584655800,eng,179.0,1,1,University Press of New England,2007

In [12]:
df[(df['average_rating'] > 4.5) & (df['ratings_count'] < 10)].shape

(25, 10)

In [13]:
mean_rating = df.groupby('language_code')['average_rating'].mean()['eng']
print(f"Mean average_rating for 'eng' books: {mean_rating}")

Mean average_rating for 'eng' books: 3.931142857142857

In [14]:
df.iloc[0:5,0:4]

,title,author,average_rating,isbn13
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222
2,Breach of Promise,James Scott Bell,4.00,9780310243878
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066

In [15]:
df.loc[[1, 4], ['language_code', 'num_pages', 'ratings_count']]

  language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [17]:
# Count books published in 2010
count_2010 = (df['year'] == 2010).sum()

print(f"Number of books published in 2010: {count_2010}")

Number of books published in 2010: 15

In [18]:
# Filter for DAW publications with average_rating > 4
authors = df[(df['publisher'] == 'DAW') & (df['average_rating'] > 4)]['author'].unique()

print("Authors with DAW publications and average_rating > 4:")
print(authors)

Authors with DAW publications and average_rating > 4:
['Mercedes Lackey' 'Sharon Green']

In [19]:
# Count books with more than 500 pages published after 2010
count = df[(df['num_pages'] > 500) & (df['year'] > 2010)].shape[0]

print(f"Number of books with more than 500 pages published after 2010: {count}")

Number of books with more than 500 pages published after 2010: 5

In [20]:
# Count how many books are authored by Agatha Christie
count = (df['author'] == 'Agatha Christie').sum()

print(f"Number of books written by Agatha Christie: {count}")
df['author'].value_counts().head(10)

Number of books written by Agatha Christie: 21

author
Stephen King              35
William Shakespeare       33
P.G. Wodehouse            23
Orson Scott Card          23
Agatha Christie           21
James Patterson           20
J.R.R. Tolkien            19
Mercedes Lackey           19
Roald Dahl                16
Gabriel García Márquez    16
Name: count, dtype: int64

In [ ]:
# Count books published in Spanish after 2000
count_spa = df[(df['language_code'] == 'spa') & (df['year'] > 2000)].shape[0]

print(f"Number of books published in Spanish after 2000: {count_spa}")

df_spa = df[df['language_code'] == 'spa']
df_spa_after_2000 = df_spa[df_spa['year'] > 2000]
df_spa_after_2000.shape

Number of books published in Spanish after 2000: 84

(84, 10)